import { Role, TaskStatus, TaskPriority, ExpiryStatus, Employee, Task, ExpiredItem, User, Branch } from './types';

export const BRANCHES: Branch[] = [
  { 
    id: '1', 
    name: 'Downtown Branch',
    address: '123 Market St, Downtown',
    phone: '(555) 123-4567',
    manager: 'Sarah Connor',
    status: 'Active'
  },
  { 
    id: '2', 
    name: 'North Warehouse',
    address: '456 Industrial Ave, Northside',
    phone: '(555) 987-6543',
    manager: 'John Doe',
    status: 'Active'
  },
  { 
    id: '3', 
    name: 'Eastside Outlet',
    address: '789 Retail Blvd, Eastside',
    phone: '(555) 456-7890',
    manager: 'Emily Blunt',
    status: 'Inactive'
  },
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: '1',
    employeeId: 'EMP001',
    name: 'Sarah Connor',
    avatar: 'https://picsum.photos/100/100',
    role: Role.Manager,
    branch: 'Downtown Branch',
    phone: '+1 555-0101',
    email: 'sarah@example.com',
    status: 'Active',
  },
  {
    id: '2',
    employeeId: 'EMP002',
    name: 'John Doe',
    avatar: 'https://picsum.photos/101/101',
    role: Role.Employee,
    branch: 'North Warehouse',
    phone: '+1 555-0102',
    email: 'john@example.com',
    status: 'Active',
  },
  {
    id: '3',
    employeeId: 'EMP003',
    name: 'Emily Blunt',
    avatar: 'https://picsum.photos/102/102',
    role: Role.Employee,
    branch: 'Downtown Branch',
    phone: '+1 555-0103',
    email: 'emily@example.com',
    status: 'Inactive',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: '101',
    title: 'Audit Dairy Section',
    description: 'Check all milk and cheese expiry dates.',
    assignedBy: 'Sarah Connor',
    assignedTo: 'John Doe',
    branch: 'North Warehouse',
    priority: TaskPriority.High,
    dueDate: '2023-11-20',
    status: TaskStatus.Open,
  },
  {
    id: '102',
    title: 'Restock Shelf A',
    description: 'Refill the cereal aisle.',
    assignedBy: 'Sarah Connor',
    assignedTo: 'Emily Blunt',
    branch: 'Downtown Branch',
    priority: TaskPriority.Medium,
    dueDate: '2023-11-18',
    status: TaskStatus.Overdue,
  },
  {
    id: '103',
    title: 'Monthly Cleanup',
    description: 'Deep clean the storage room.',
    assignedBy: 'Admin',
    assignedTo: 'John Doe',
    branch: 'North Warehouse',
    priority: TaskPriority.Low,
    dueDate: '2023-11-25',
    status: TaskStatus.InProgress,
  },
];

export const MOCK_EXPIRED_ITEMS: ExpiredItem[] = [
  {
    id: '201',
    productName: 'Organic Whole Milk',
    unitName: '1L Carton',
    barcode: '883471002',
    remainingQty: 15,
    mfgDate: '2023-11-01',
    expDate: '2023-11-15',
    branch: 'Downtown Branch',
    status: ExpiryStatus.Critical,
  },
  {
    id: '202',
    productName: 'Cheddar Cheese Block',
    unitName: '500g',
    barcode: '883471055',
    remainingQty: 4,
    mfgDate: '2023-10-01',
    expDate: '2023-11-10',
    branch: 'North Warehouse',
    status: ExpiryStatus.Expired,
  },
  {
    id: '203',
    productName: 'Spicy Tomato Sauce',
    unitName: 'Jar',
    barcode: '883471099',
    remainingQty: 50,
    mfgDate: '2023-01-15',
    expDate: '2024-01-15',
    branch: 'Eastside Outlet',
    status: ExpiryStatus.Good,
  },
  {
    id: '204',
    productName: 'Sourdough Bread',
    unitName: 'Loaf',
    barcode: '883471112',
    remainingQty: 8,
    mfgDate: '2023-11-14',
    expDate: '2023-11-21',
    branch: 'Downtown Branch',
    status: ExpiryStatus.Critical,
  },
  {
    id: '205',
    productName: 'Chicken Breast',
    unitName: 'kg',
    barcode: '883472222',
    remainingQty: 20,
    mfgDate: '2023-11-10',
    expDate: '2023-11-18',
    branch: 'North Warehouse',
    status: ExpiryStatus.Critical,
  },
  {
    id: '206',
    productName: 'Frozen Peas',
    unitName: 'Bag',
    barcode: '883473333',
    remainingQty: 100,
    mfgDate: '2023-08-01',
    expDate: '2024-08-01',
    branch: 'Eastside Outlet',
    status: ExpiryStatus.Safe,
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Liam Parker',
    email: 'admin@company.com',
    role: Role.Admin,
    branchId: 'all',
    status: 'Active',
    lastActive: 'Just now',
  },
  {
    id: 'u2',
    name: 'Sarah Manager',
    email: 'sarah@company.com',
    role: Role.Manager,
    branchId: '1',
    status: 'Active',
    lastActive: '2 hours ago',
  },
];
